import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { Screen } from '../components/ui/Screen';
import { colors, spacing } from '../constants/theme';
import { useAuth } from '../providers/AuthProvider';

export default function AuthScreen() {
  const { state, signIn } = useAuth();
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  return <Screen eyebrow="SAIS authentication" title="Sign in to your workspace" description="Secure access to your school operations, people, and academic records."><View style={styles.formCard}><Text style={styles.formTitle}>Welcome back</Text><Text style={styles.formHint}>Use your work email and password to continue.</Text><Text style={styles.label}>EMAIL OR USERNAME</Text><TextInput autoCapitalize="none" autoCorrect={false} keyboardType="email-address" placeholder="you@school.edu" placeholderTextColor={colors.muted} value={identifier} onChangeText={setIdentifier} style={styles.input} /><Text style={styles.label}>PASSWORD</Text><TextInput placeholder="Enter your password" placeholderTextColor={colors.muted} secureTextEntry value={password} onChangeText={setPassword} style={styles.input} /><Text accessibilityRole="alert" style={styles.error}>{state.status === 'error' ? state.message : ''}</Text><Pressable accessibilityRole="button" onPress={() => signIn(identifier, password)} style={styles.button}><Text style={styles.buttonText}>Sign in</Text><Text style={styles.buttonArrow}>→</Text></Pressable></View></Screen>;
}
const styles = StyleSheet.create({ formCard: { backgroundColor: colors.white, borderColor: colors.line, borderRadius: 24, borderWidth: 1, padding: spacing.lg, shadowColor: colors.ink, shadowOpacity: 0.08, shadowRadius: 18, elevation: 3 }, formTitle: { color: colors.ink, fontSize: 22, fontWeight: '800' }, formHint: { color: colors.muted, fontSize: 14, lineHeight: 20, marginBottom: spacing.lg, marginTop: spacing.xs }, label: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 0.8, marginBottom: spacing.xs, marginTop: spacing.sm }, input: { backgroundColor: colors.paper, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 16, padding: spacing.md }, error: { color: colors.danger, minHeight: 24, paddingTop: spacing.xs }, button: { alignItems: 'center', backgroundColor: colors.blue, borderRadius: 12, flexDirection: 'row', justifyContent: 'center', padding: spacing.md }, buttonText: { color: colors.white, fontSize: 16, fontWeight: '800' }, buttonArrow: { color: colors.white, fontSize: 20, marginLeft: spacing.sm } });
