-- Backend 4 baseline: the connected PostgreSQL database already contains the SAIS schema from the prior migration history.
-- This migration is intentionally a no-op so production deployment never attempts to recreate existing enums/tables.
-- Future schema changes must be additive and generated from the schema that matches the connected database.
