CREATE TYPE "ClassStatus" AS ENUM ('PLANNED', 'ACTIVE', 'CANCELLED', 'ARCHIVED');
CREATE TABLE "GradeLevel" ("id" UUID NOT NULL, "tenantId" UUID NOT NULL, "schoolId" UUID NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, CONSTRAINT "GradeLevel_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "GradeLevel_tenantId_schoolId_code_key" ON "GradeLevel"("tenantId", "schoolId", "code");
CREATE TABLE "Classroom" ("id" UUID NOT NULL, "tenantId" UUID NOT NULL, "schoolId" UUID NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "capacity" INTEGER NOT NULL, CONSTRAINT "Classroom_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Classroom_tenantId_schoolId_code_key" ON "Classroom"("tenantId", "schoolId", "code");
CREATE TABLE "Class" ("id" UUID NOT NULL, "tenantId" UUID NOT NULL, "schoolId" UUID NOT NULL, "academicYearId" UUID NOT NULL, "gradeLevelId" UUID NOT NULL, "classroomId" UUID, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "section" TEXT, "capacity" INTEGER NOT NULL, "status" "ClassStatus" NOT NULL DEFAULT 'PLANNED', "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Class_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Class_tenantId_schoolId_academicYearId_code_key" ON "Class"("tenantId", "schoolId", "academicYearId", "code");
CREATE INDEX "Class_tenantId_schoolId_status_idx" ON "Class"("tenantId", "schoolId", "status");
CREATE TABLE "ClassEnrollment" ("classId" UUID NOT NULL, "studentId" UUID NOT NULL, "tenantId" UUID NOT NULL, "schoolId" UUID NOT NULL, "status" "EnrollmentStatus" NOT NULL DEFAULT 'ACTIVE', "enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "endedAt" TIMESTAMP(3), CONSTRAINT "ClassEnrollment_pkey" PRIMARY KEY ("classId", "studentId"));
CREATE INDEX "ClassEnrollment_tenantId_schoolId_status_idx" ON "ClassEnrollment"("tenantId", "schoolId", "status");
CREATE TABLE "ClassTeacher" ("classId" UUID NOT NULL, "teacherId" UUID NOT NULL, "isLead" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "ClassTeacher_pkey" PRIMARY KEY ("classId", "teacherId"));
CREATE TABLE "ClassSubject" ("classId" UUID NOT NULL, "subjectId" UUID NOT NULL, CONSTRAINT "ClassSubject_pkey" PRIMARY KEY ("classId", "subjectId"));
CREATE TABLE "ClassHistory" ("id" UUID NOT NULL, "classId" UUID NOT NULL, "fromStatus" "ClassStatus" NOT NULL, "toStatus" "ClassStatus" NOT NULL, "actorId" UUID, "reason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ClassHistory_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ClassHistory_classId_createdAt_idx" ON "ClassHistory"("classId", "createdAt");
ALTER TABLE "GradeLevel" ADD CONSTRAINT "GradeLevel_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GradeLevel" ADD CONSTRAINT "GradeLevel_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Classroom" ADD CONSTRAINT "Classroom_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Classroom" ADD CONSTRAINT "Classroom_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Class" ADD CONSTRAINT "Class_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Class" ADD CONSTRAINT "Class_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Class" ADD CONSTRAINT "Class_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Class" ADD CONSTRAINT "Class_gradeLevelId_fkey" FOREIGN KEY ("gradeLevelId") REFERENCES "GradeLevel"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Class" ADD CONSTRAINT "Class_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "Classroom"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ClassEnrollment" ADD CONSTRAINT "ClassEnrollment_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassEnrollment" ADD CONSTRAINT "ClassEnrollment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassEnrollment" ADD CONSTRAINT "ClassEnrollment_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassEnrollment" ADD CONSTRAINT "ClassEnrollment_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassTeacher" ADD CONSTRAINT "ClassTeacher_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassTeacher" ADD CONSTRAINT "ClassTeacher_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassSubject" ADD CONSTRAINT "ClassSubject_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassSubject" ADD CONSTRAINT "ClassSubject_subjectId_fkey" FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassHistory" ADD CONSTRAINT "ClassHistory_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE CASCADE ON UPDATE CASCADE;
