import { randomUUID } from 'node:crypto';

const demoEvidence = [
  {
    sourceType: 'attendance',
    sourceRef: 'attendance-jan-2026',
    label: 'Attendance rate',
    value: { current: 94.8, target: 95, unit: '%' },
  },
  {
    sourceType: 'finance',
    sourceRef: 'collections-jan-2026',
    label: 'Fee collection',
    value: { current: 91.6, target: 93, unit: '%' },
  },
  {
    sourceType: 'learning',
    sourceRef: 'engagement-jan-2026',
    label: 'Learning engagement',
    value: { current: 87.2, target: 85, unit: '%' },
  },
];

export const aiReportDemo = {
  report: {
    id: 'demo-report-annual-review',
    title: 'January school performance brief',
    period: 'January 2026',
    status: 'NEEDS_REVIEW',
    version: 3,
    template: 'Executive performance brief',
  },
  sections: [
    {
      key: 'executive-summary',
      title: 'Executive summary',
      narrative:
        'School performance is trending positively: engagement is above target and attendance is close to the operating threshold. Finance collections improved, while Grade 9 attendance needs a focused intervention.',
      confidence: 92,
    },
    {
      key: 'academic-outlook',
      title: 'Academic outlook',
      narrative:
        'Learning engagement reached 87.2%, exceeding the 85% target. The strongest signal is sustained improvement across the last three reporting periods.',
      confidence: 89,
    },
    {
      key: 'recommended-actions',
      title: 'Recommended actions',
      narrative:
        'Review Grade 9 attendance drivers, keep the current engagement routines, and schedule a finance collection checkpoint before the next reporting close.',
      confidence: 86,
    },
  ],
  evidence: demoEvidence,
  limitations: [
    'Narrative is grounded in the evidence listed below.',
    'Recommendations require human review before publication.',
    'No student-level diagnosis is generated by this report.',
  ],
  reports: [
    { name: 'January school performance brief', status: 'Needs review', updated: '12 minutes ago' },
    { name: 'Attendance intervention digest', status: 'Approved', updated: 'Yesterday' },
    { name: 'Term finance narrative', status: 'Draft', updated: 'Jan 28, 2026' },
  ],
};

function requireTenant(tenantId) {
  if (!tenantId) throw new Error('Tenant scope required');
}

export function getReportOverview({ tenantId }) {
  requireTenant(tenantId);
  return { ...aiReportDemo, tenantId, generatedAt: '2026-01-31T06:00:00.000Z' };
}

export function validateReport({ tenantId, report = aiReportDemo }) {
  requireTenant(tenantId);
  const evidenceText = JSON.stringify(report.evidence).toLowerCase();
  const claims = report.sections.flatMap(
    (section) => section.narrative.match(/\d+(?:\.\d+)?%?/g) || []
  );
  const unsupportedClaims = claims.filter((claim) => !evidenceText.includes(claim.toLowerCase()));
  return {
    valid: unsupportedClaims.length === 0,
    unsupportedClaims,
    checkedSections: report.sections.length,
    evidenceItems: report.evidence.length,
  };
}

export function requestGeneration({
  tenantId,
  templateKey = 'executive-performance',
  period = 'January 2026',
}) {
  requireTenant(tenantId);
  if (
    !['executive-performance', 'attendance-intervention', 'finance-narrative'].includes(templateKey)
  )
    throw new Error('Unsupported report template');
  return {
    id: randomUUID(),
    status: 'QUEUED',
    templateKey,
    period,
    requiresReview: true,
    evidencePolicy: 'approved-sources-only',
  };
}

export function approveReport({ tenantId, reportId, reviewerId }) {
  requireTenant(tenantId);
  if (!reportId || !reviewerId) throw new Error('Report and reviewer are required');
  return { reportId, status: 'APPROVED', version: 4, approvedBy: 'authorized reviewer' };
}

export function requestReportExport({ tenantId, reportId, format = 'pdf' }) {
  requireTenant(tenantId);
  if (!['pdf', 'docx', 'csv'].includes(format)) throw new Error('Unsupported report format');
  return { id: randomUUID(), reportId, format, status: 'QUEUED', scope: 'tenant' };
}
