import { Router } from 'express';
import documentationRoutes from './documentationRoutes.js';
import healthRoutes from './healthRoutes.js';
import authRoutes from './authRoutes.js';
import rbacRoutes from './rbacRoutes.js';
import userRoutes from './userRoutes.js';
import schoolRoutes from './schoolRoutes.js';
import studentDomainRoutes from './studentDomainRoutes.js';
import parentRoutes from './parentRoutes.js';
import teacherRoutes from './teacherRoutes.js';
import subjectRoutes from './subjectRoutes.js';
import classRoutes from './classRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import academicPeriodRoutes from './academicPeriodRoutes.js';
import academicPolicyRoutes from './academicPolicyRoutes.js';
import tenantAdminRoutes from './tenantAdminRoutes.js';
import platformAdminRoutes from './platformAdminRoutes.js';
import activationRoutes from './activationRoutes.js';
import accountRoutes from './accountRoutes.js';
import tenantLifecycleRoutes from './tenantLifecycleRoutes.js';
import { featureUnavailableRoutes } from './featureUnavailableRoutes.js';
import examinationRoutes from './examinationRoutes.js';
import timetableRoutes from './timetableRoutes.js';
import communicationRoutes from './communicationRoutes.js';
import hrRoutes from './hrRoutes.js';

const router = Router();

// ─── System health probes ──────────────────────────────────────────────────────
router.use('/', healthRoutes);
router.use('/', documentationRoutes);
router.use('/auth', authRoutes);
router.use('/rbac', rbacRoutes);
router.use('/users', userRoutes);
router.use('/schools', schoolRoutes);
router.use('/students', studentDomainRoutes);
router.use('/parents', parentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/subjects', subjectRoutes);
router.use('/classes', classRoutes);
router.use('/finance', featureUnavailableRoutes('Finance', 'FIN-001'));
router.use('/payment-gateway', featureUnavailableRoutes('Payment gateway', 'PAY-001'));
router.use('/payment/monime/webhook', featureUnavailableRoutes('Payment webhook', 'PAY-001'));
router.use('/academic-periods', academicPeriodRoutes);
router.use('/academic-policies', academicPolicyRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/examinations', examinationRoutes);
router.use('/results', featureUnavailableRoutes('Results', 'RES-001'));
router.use('/timetables', timetableRoutes);
router.use('/communication', communicationRoutes);
router.use('/hr', hrRoutes);
router.use('/libraries', featureUnavailableRoutes('Library', 'LIB-001'));
router.use('/assets-inventory', featureUnavailableRoutes('Assets and inventory', 'AST-001'));
router.use('/transport', featureUnavailableRoutes('Transport', 'TRN-001'));
router.use('/boarding', featureUnavailableRoutes('Boarding', 'BRD-001'));
router.use('/security', featureUnavailableRoutes('Security operations', 'SEC-001'));
router.use('/analytics', featureUnavailableRoutes('Analytics', 'ANA-001'));
router.use('/ai-intelligence', featureUnavailableRoutes('AI intelligence', 'AI-001'));
router.use('/smart-identity', featureUnavailableRoutes('Smart identity', 'BIO-001'));
router.use('/iot', featureUnavailableRoutes('IoT', 'IOT-001'));
router.use('/tenant-admin', tenantAdminRoutes);
router.use('/billing', featureUnavailableRoutes('Subscription billing', 'SaaS-001'));
router.use('/platform-admin', platformAdminRoutes);
router.use('/security-admin', featureUnavailableRoutes('Security administration', 'SEC-001'));
router.use('/ai-academic', featureUnavailableRoutes('AI academic assistant', 'AI-001'));
router.use('/ai-reports', featureUnavailableRoutes('AI reports', 'AI-001'));
router.use('/ai-chat', featureUnavailableRoutes('AI chat', 'AI-001'));
router.use('/integrations', featureUnavailableRoutes('External integrations', 'INT-001'));
router.use('/biometrics', featureUnavailableRoutes('Biometrics', 'BIO-001'));
router.use('/activation-requests', activationRoutes);
router.use('/account', accountRoutes);
router.use('/tenants', tenantLifecycleRoutes);

export default router;
