import { Router } from 'express';
import documentationRoutes from './documentationRoutes.js';
import healthRoutes from './healthRoutes.js';
import authRoutes from './authRoutes.js';
import rbacRoutes from './rbacRoutes.js';
import userRoutes from './userRoutes.js';
import schoolRoutes from './schoolRoutes.js';
import studentDomainRoutes from './studentDomainRoutes.js';
import parentRoutes from './parentRoutes.js';
import teacherRoutes from './teacherRoutes.js';
import subjectRoutes from './subjectRoutes.js';
import classRoutes from './classRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import academicPeriodRoutes from './academicPeriodRoutes.js';
import academicPolicyRoutes from './academicPolicyRoutes.js';
import { featureUnavailableRoutes } from './featureUnavailableRoutes.js';
import examinationRoutes from './examinationRoutes.js';
import resultRoutes from './resultRoutes.js';
import timetableRoutes from './timetableRoutes.js';
import financeRoutes from './financeRoutes.js';
import paymentGatewayRoutes, { monimeWebhookHandler } from './paymentGatewayRoutes.js';
import communicationRoutes from './communicationRoutes.js';
import hrRoutes from './hrRoutes.js';
import libraryRoutes from './libraryRoutes.js';
import assetInventoryRoutes from './assetInventoryRoutes.js';
import transportRoutes from './transportRoutes.js';
import boardingRoutes from './boardingRoutes.js';
import classroomStreamRoutes from './classroomStreamRoutes.js';
import assignmentRoutes from './assignmentRoutes.js';
import classroomLiveSessionRoutes from './classroomLiveSessionRoutes.js';
import materialRoutes from './materialRoutes.js';
import submissionRoutes from './submissionRoutes.js';
import billingRoutes from './billingRoutes.js';
import gradebookRoutes from './gradebookRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import searchRoutes from './searchRoutes.js';

const router = Router();

// ─── System health probes ──────────────────────────────────────────────────────
router.use('/', healthRoutes);
router.use('/', documentationRoutes);
router.use('/auth', authRoutes);
router.use('/rbac', rbacRoutes);
router.use('/users', userRoutes);
router.use('/schools', schoolRoutes);
router.use('/students', studentDomainRoutes);
router.use('/parents', parentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/subjects', subjectRoutes);
router.use('/classes', classRoutes);
router.use('/finance', financeRoutes);
router.use('/payment-gateway', paymentGatewayRoutes);
router.post('/payment/monime/webhook', monimeWebhookHandler);
router.use('/academic-periods', academicPeriodRoutes);
router.use('/academic-policies', academicPolicyRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/examinations', examinationRoutes);
router.use('/results', resultRoutes);
router.use('/timetables', timetableRoutes);
router.use('/communication', communicationRoutes);
router.use('/hr', hrRoutes);
router.use('/libraries', libraryRoutes);
router.use('/assets-inventory', assetInventoryRoutes);
router.use('/transport', transportRoutes);
router.use('/boarding', boardingRoutes);
router.use('/classroom-stream', classroomStreamRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/materials', materialRoutes);
router.use('/submissions', submissionRoutes);
router.use('/lms/live-sessions', classroomLiveSessionRoutes);
router.use('/security', featureUnavailableRoutes('Security operations', 'SEC-001'));
router.use('/analytics', analyticsRoutes);
router.use('/ai-intelligence', featureUnavailableRoutes('AI intelligence', 'AI-001'));
router.use('/smart-identity', featureUnavailableRoutes('Smart identity', 'BIO-001'));
router.use('/iot', featureUnavailableRoutes('IoT', 'IOT-001'));
router.use('/billing', billingRoutes);
router.use('/lms/gradebook', gradebookRoutes);
router.use('/lms/search', searchRoutes);
router.use('/search', searchRoutes);
router.use('/security-admin', featureUnavailableRoutes('Security administration', 'SEC-001'));
router.use('/ai-academic', featureUnavailableRoutes('AI academic assistant', 'AI-001'));
router.use('/ai-reports', featureUnavailableRoutes('AI reports', 'AI-001'));
router.use('/ai-chat', featureUnavailableRoutes('AI chat', 'AI-001'));
router.use('/integrations', featureUnavailableRoutes('External integrations', 'INT-001'));
router.use('/biometrics', featureUnavailableRoutes('Biometrics', 'BIO-001'));

export default router;
