import { Router } from 'express';
import documentationRoutes from './documentationRoutes.js';
import healthRoutes from './healthRoutes.js';
import authRoutes from './authRoutes.js';
import rbacRoutes from './rbacRoutes.js';
import userRoutes from './userRoutes.js';
import schoolRoutes from './schoolRoutes.js';
import studentRoutes from './studentRoutes.js';
import parentRoutes from './parentRoutes.js';
import teacherRoutes from './teacherRoutes.js';
import classRoutes from './classRoutes.js';
import financeRoutes from './financeRoutes.js';
import financeCoreRoutes from './financeCoreRoutes.js';
import paymentGatewayRoutes from './paymentGatewayRoutes.js';
import academicPeriodRoutes from './academicPeriodRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import examinationRoutes from './examinationRoutes.js';
import resultRoutes from './resultRoutes.js';
import timetableRoutes from './timetableRoutes.js';
import communicationRoutes from './communicationRoutes.js';
import hrRoutes from './hrRoutes.js';
import libraryRoutes from './libraryRoutes.js';
import assetInventoryRoutes from './assetInventoryRoutes.js';
import transportRoutes from './transportRoutes.js';
import boardingRoutes from './boardingRoutes.js';
import securityRoutes from './securityRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import aiIntelligenceRoutes from './aiIntelligenceRoutes.js';
import smartIdentityRoutes from './smartIdentityRoutes.js';
import iotRoutes from './iotRoutes.js';
import tenantAdminRoutes from './tenantAdminRoutes.js';
import billingRoutes from './billingRoutes.js';
import platformAdminRoutes from './platformAdminRoutes.js';
import securityAdminRoutes from './securityAdminRoutes.js';
import aiAcademicRoutes from './aiAcademicRoutes.js';
import aiReportRoutes from './aiReportRoutes.js';
import aiChatRoutes from './aiChatRoutes.js';
import integrationRoutes from './integrationRoutes.js';
import biometricRoutes from './biometricRoutes.js';
import activationRoutes from './activationRoutes.js';

const router = Router();

// ─── System health probes ──────────────────────────────────────────────────────
router.use('/', healthRoutes);
router.use('/', documentationRoutes);
router.use('/auth', authRoutes);
router.use('/rbac', rbacRoutes);
router.use('/users', userRoutes);
router.use('/schools', schoolRoutes);
router.use('/students', studentRoutes);
router.use('/parents', parentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/classes', classRoutes);
router.use('/finance', financeRoutes);
router.use('/finance/core', financeCoreRoutes);
router.use('/payment-gateway', paymentGatewayRoutes);
router.use('/academic-periods', academicPeriodRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/examinations', examinationRoutes);
router.use('/results', resultRoutes);
router.use('/timetables', timetableRoutes);
router.use('/communication', communicationRoutes);
router.use('/hr', hrRoutes);
router.use('/libraries', libraryRoutes);
router.use('/assets-inventory', assetInventoryRoutes);
router.use('/transport', transportRoutes);
router.use('/boarding', boardingRoutes);
router.use('/security', securityRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/ai-intelligence', aiIntelligenceRoutes);
router.use('/smart-identity', smartIdentityRoutes);
router.use('/iot', iotRoutes);
router.use('/tenant-admin', tenantAdminRoutes);
router.use('/billing', billingRoutes);
router.use('/platform-admin', platformAdminRoutes);
router.use('/security-admin', securityAdminRoutes);
router.use('/ai-academic', aiAcademicRoutes);
router.use('/ai-reports', aiReportRoutes);
router.use('/ai-chat', aiChatRoutes);
router.use('/integrations', integrationRoutes);
router.use('/biometrics', biometricRoutes);
router.use('/activation-requests', activationRoutes);

export default router;
